/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ujaen.ssmmaa.gui;

/**
 *
 * @author danie
 */
public class AgenteRatonJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AgenteRatonJFrame
     */
    private int cheeseCount = 0;
    private int numPartidasJugadass = 0;
    private int numPartidasJugadasActualmentee = 0;
    private int numPartidasGanadass = 0;

    public AgenteRatonJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numQuesos = new javax.swing.JLabel();
        numPartidasJugadas = new javax.swing.JLabel();
        numPartidasJugadasActualmente = new javax.swing.JLabel();
        numPartidasGanadas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numQuesos.setText("jLabel1");

        numPartidasJugadas.setText("jLabel2");

        numPartidasJugadasActualmente.setText("jLabel1");

        numPartidasGanadas.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numPartidasGanadas)
                    .addComponent(numPartidasJugadasActualmente)
                    .addComponent(numPartidasJugadas)
                    .addComponent(numQuesos))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(numQuesos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numPartidasJugadas)
                .addGap(31, 31, 31)
                .addComponent(numPartidasJugadasActualmente)
                .addGap(26, 26, 26)
                .addComponent(numPartidasGanadas)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void incrementCheese() {
        cheeseCount++;
        numQuesos.setText("Número de quesos: " + cheeseCount);
    }

    public void incrementPartidasJugadas() {
        numPartidasJugadass++;
        numPartidasJugadas.setText("Número de partidas jugadas: " + numPartidasGanadass);
    }

    public void incrementPartidasJugadasActualmente() {
        numPartidasJugadasActualmentee++;
        numPartidasJugadasActualmente.setText("Número de partidas jugadas actualmente: " + numPartidasJugadasActualmentee);
    }

    public void incrementPartidasGanadas() {
        numPartidasGanadass++;
        numPartidasGanadas.setText("Numero de partidas ganadas" + numPartidasGanadass);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel numPartidasGanadas;
    private javax.swing.JLabel numPartidasJugadas;
    private javax.swing.JLabel numPartidasJugadasActualmente;
    private javax.swing.JLabel numQuesos;
    // End of variables declaration//GEN-END:variables
}
