/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ujaen.ssmmaa.gui;

import es.ujaen.ssmmaa.agentes.AgenteRaton;

/**
 *
 * @author danie
 */
public class AgenteRatonJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AgenteRatonJFrame
     */
    private int cheeseCount = 0;
    private int numPartidasJugadass = 0;
    private int numPartidasJugadasActualmentee = 0;
    private int numPartidasGanadass = 0;

    private AgenteRaton myAgent;

    public AgenteRatonJFrame(AgenteRaton myAgent) {
        initComponents();
        this.myAgent = myAgent;

        this.setTitle(this.myAgent.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numQuesos = new javax.swing.JLabel();
        numPartidasJugadas = new javax.swing.JLabel();
        numPartidasJugadasActualmente = new javax.swing.JLabel();
        numPartidasGanadas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salidaTexto = new javax.swing.JTextArea();
        FInalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numQuesos.setText("numQuesos: 0");

        numPartidasJugadas.setText("numPartidasJugadas: 0");

        numPartidasJugadasActualmente.setText("numPartJugActualmente: 0");

        numPartidasGanadas.setText("numPartidasGanadas: 0");

        salidaTexto.setColumns(20);
        salidaTexto.setRows(5);
        jScrollPane1.setViewportView(salidaTexto);

        FInalizar.setText("Finalizar");
        FInalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FInalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numPartidasGanadas)
                    .addComponent(numPartidasJugadasActualmente)
                    .addComponent(numPartidasJugadas)
                    .addComponent(numQuesos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FInalizar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(numQuesos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numPartidasJugadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numPartidasJugadasActualmente)
                        .addGap(18, 18, 18)
                        .addComponent(numPartidasGanadas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(FInalizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FInalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FInalizarActionPerformed
        myAgent.doDelete();
    }//GEN-LAST:event_FInalizarActionPerformed

    public void presentarSalida(String msg) {
        salidaTexto.append(msg + "\n");
        System.out.println(msg);
    }

    public void incrementCheese() {
        cheeseCount++;
        numQuesos.setText("Número de quesos: " + cheeseCount);
    }

    public void incrementPartidasJugadas() {
        numPartidasJugadass++;
        numPartidasJugadas.setText("Número de partidas jugadas: " + numPartidasGanadass);
    }

    public void incrementPartidasJugadasActualmente() {
        numPartidasJugadasActualmentee++;
        numPartidasJugadasActualmente.setText("Número de partidas jugadas actualmente: " + numPartidasJugadasActualmentee);
    }

    public void incrementPartidasGanadas() {
        numPartidasGanadass++;
        numPartidasGanadas.setText("Numero de partidas ganadas" + numPartidasGanadass);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FInalizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numPartidasGanadas;
    private javax.swing.JLabel numPartidasJugadas;
    private javax.swing.JLabel numPartidasJugadasActualmente;
    private javax.swing.JLabel numQuesos;
    private javax.swing.JTextArea salidaTexto;
    // End of variables declaration//GEN-END:variables
}
